services:
  chemist-engine-reaktoro:
    build:
      context: ./reaktoro
      dockerfile: Dockerfile.reaktoro
    ports:
      - "50051:50051"
    restart: unless-stopped

  chemist-engine-catalyst-jl:
    build:
      context: ./catalyst
      dockerfile: Dockerfile.catalyst-jl
    ports:
      - "8082:8082"
    restart: unless-stopped
