services:
  chemist-engine-flask:
    container_name: chemist-engine-flask
    build:
      context: ./reaktoro
      dockerfile: Dockerfile.reaktoro
    command: [ "/bin/bash", "-c", "/app/src/start_flask.sh" ]
    ports:
      - "5000:5000"
    restart: unless-stopped

  chemist-engine-catalyst-jl:
    container_name: chemist-engine-catalyst-jl
    build:
      context: ./catalyst
      dockerfile: Dockerfile.catalyst-jl
    ports:
      - "8082:8082"
    restart: unless-stopped
