# Start from Ubuntu base image
FROM ubuntu:22.04

RUN apt-get update && apt-get install -y \
  wget \
  build-essential \
  cmake \
  git \
  unzip \
  libssl-dev

RUN wget https://repo.anaconda.com/archive/Anaconda3-2024.10-1-Linux-x86_64.sh -O /tmp/Anaconda3-2024.10-1-Linux-x86_64.sh && \
  bash /tmp/Anaconda3-2024.10-1-Linux-x86_64.sh -b -p /opt/conda && \
  rm /tmp/Anaconda3-2024.10-1-Linux-x86_64.sh

ENV PATH="/opt/conda/bin:$PATH"

RUN conda update -n base -c defaults conda -y && \
  conda config --add channels conda-forge

# Create 'rkt' environment and install Reaktoro
RUN conda create -n rkt -c conda-forge reaktoro -y

WORKDIR /app

# Ensure the Conda environment is activated when the container runs
# We add a shell hook to activate the 'rkt' environment automatically
SHELL ["conda", "run", "-n", "rkt", "/bin/bash", "-c"]

# RUN apt-get update && apt-get install -y protobuf-compiler

# RUN python -m grpc_tools.protoc -I/app/src --python_out=/app/src --grpc_python_out=/app/src /app/src/reactions.proto

COPY requirements.txt /app/
COPY src/reactions_pb2.py src/reactions_pb2_grpc.py /app/src/


RUN conda run -n rkt pip install -r requirements.txt

COPY . /app

# Expose the application port
EXPOSE 5000

# Use ENTRYPOINT with Conda environment activated
ENTRYPOINT ["conda", "run", "--no-capture-output", "-n", "rkt", "python", "src/app.py"]

