# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import reactions_pb2 as reactions__pb2

GRPC_GENERATED_VERSION = '1.67.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in reactions_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ChemistryServiceStub(object):
    """Define the service with both methods
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ComputeReaction = channel.unary_unary(
                '/chemistry.ChemistryService/ComputeReaction',
                request_serializer=reactions__pb2.ReactionRequest.SerializeToString,
                response_deserializer=reactions__pb2.ReactionResponse.FromString,
                _registered_method=True)
        self.ComputeThermodynamics = channel.unary_unary(
                '/chemistry.ChemistryService/ComputeThermodynamics',
                request_serializer=reactions__pb2.ThermodynamicsRequest.SerializeToString,
                response_deserializer=reactions__pb2.ThermodynamicsResponse.FromString,
                _registered_method=True)


class ChemistryServiceServicer(object):
    """Define the service with both methods
    """

    def ComputeReaction(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ComputeThermodynamics(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ChemistryServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ComputeReaction': grpc.unary_unary_rpc_method_handler(
                    servicer.ComputeReaction,
                    request_deserializer=reactions__pb2.ReactionRequest.FromString,
                    response_serializer=reactions__pb2.ReactionResponse.SerializeToString,
            ),
            'ComputeThermodynamics': grpc.unary_unary_rpc_method_handler(
                    servicer.ComputeThermodynamics,
                    request_deserializer=reactions__pb2.ThermodynamicsRequest.FromString,
                    response_serializer=reactions__pb2.ThermodynamicsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'chemistry.ChemistryService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('chemistry.ChemistryService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ChemistryService(object):
    """Define the service with both methods
    """

    @staticmethod
    def ComputeReaction(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/chemistry.ChemistryService/ComputeReaction',
            reactions__pb2.ReactionRequest.SerializeToString,
            reactions__pb2.ReactionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ComputeThermodynamics(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/chemistry.ChemistryService/ComputeThermodynamics',
            reactions__pb2.ThermodynamicsRequest.SerializeToString,
            reactions__pb2.ThermodynamicsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
