# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: reactions.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'reactions.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0freactions.proto\x12\tchemistry\"9\n\x0fReactionRequest\x12\x0f\n\x07species\x18\x01 \x01(\t\x12\x15\n\rrate_constant\x18\x02 \x01(\x01\"\"\n\x10ReactionResponse\x12\x0e\n\x06result\x18\x01 \x01(\t\"+\n\x15ThermodynamicsRequest\x12\x12\n\nparameters\x18\x01 \x01(\t\"(\n\x16ThermodynamicsResponse\x12\x0e\n\x06result\x18\x01 \x01(\t2\xbc\x01\n\x10\x43hemistryService\x12J\n\x0f\x43omputeReaction\x12\x1a.chemistry.ReactionRequest\x1a\x1b.chemistry.ReactionResponse\x12\\\n\x15\x43omputeThermodynamics\x12 .chemistry.ThermodynamicsRequest\x1a!.chemistry.ThermodynamicsResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'reactions_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_REACTIONREQUEST']._serialized_start=30
  _globals['_REACTIONREQUEST']._serialized_end=87
  _globals['_REACTIONRESPONSE']._serialized_start=89
  _globals['_REACTIONRESPONSE']._serialized_end=123
  _globals['_THERMODYNAMICSREQUEST']._serialized_start=125
  _globals['_THERMODYNAMICSREQUEST']._serialized_end=168
  _globals['_THERMODYNAMICSRESPONSE']._serialized_start=170
  _globals['_THERMODYNAMICSRESPONSE']._serialized_end=210
  _globals['_CHEMISTRYSERVICE']._serialized_start=213
  _globals['_CHEMISTRYSERVICE']._serialized_end=401
# @@protoc_insertion_point(module_scope)
